### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by peter2141** [europ/KNBH#1]
On my system (Ubuntu 16.04.03) when I run the script with ping everybody is online.

 
![screenshot from 2018-03-12 18-52-55](https://user-images.githubusercontent.com/22367448/37300595-a164169e-2626-11e8-9a36-0ad79ea31c16.png)

@europ Please add your screenshot to comment.

**Comment by europ** [comment]
Thank you for contributing @peter2141 ! It is really strange. I tried it and the most of them were offline.

**Comment by xbolva00** [comment]
Cannot reproduce. It works for me.

![image](https://user-images.githubusercontent.com/22410393/37300732-0307a24e-2627-11e8-9fd1-be1f9205ab63.png)

**Comment by europ** [comment]
@xbolva00 I am online, please can you explain why I am offline in your screenshot ?

**Comment by tammar96** [comment]
![screenshot from 2018-03-13 13-03-03](https://user-images.githubusercontent.com/3913790/37340595-ebfed8cc-26be-11e8-8f8d-b15a13238916.png)
@xbolva00 @europ I am behind NAT and it's even worse ...

**Comment by europ** [comment]
@xbolva00 please, can you fix your feature?
